title: |
  chhanz 
  기술 블로그
email: han0495@gmail.com
description: |
  소소하게 기술 자료 공유하고 있습니다.
  
baseurl: ''
url: https://chhanz.github.io
timezone: Asia/Seoul
facebook_comment: true

repository: chhanz/chhanz.github.io

permalink: /:categories/:year/:month/:day/:title/

excerpt_separator: <!--more-->

markdown: kramdown

krandown:
  input: GFM
  highlighter: rouge

plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 5
paginate_path: '/page/:num/'

collections:
  authors:
    output: true
    permalink: /authors/:path/
  tags:
    output: true
    permalink: /tags/:path/

defaults:
  - scope:
      path: ''
      type: authors
    values:
      layout: author
  - scope:
      path: ''
      type: tags
    values:
      layout: tag

exclude: [README.md, Gemfile, Gemfile.lock]

keep_files: [assets, files]

author: chhanz
image: '/assets/images/default_cover.jpg'
asset_url: /assets

google_analytics:
  ua: UA-130421804-1
#facebook:
#  app_id: ''
#  username: 
#  comment: true
#twitter:
#  username:
#google_plus:
#  username:
github:
  username: chhanz
linkedin:
username: chhanz
